import Head from 'next/head'
import ContactForm from '../components/contactForm';
import styles from '../styles/Contact.module.css';

function Contact() {
  return (
    <div>
      <Head>
        <title>Dane Walker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main id={styles.container}>
        <div id={styles.intro}>
          <h1>Contact</h1>
        </div>


        <ContactForm />
      </main>

      <footer id={styles.footer}>
        <p>&copy; Copyright 2022, Dane Walker</p>
      </footer>
      
    </div>
  )
}

export default Contact;