import Head from 'next/head'
import { useEffect, useState } from 'react'
import { Triangle } from  'react-loader-spinner'
import colours from '../components/colours';

import styles from '../styles/Home.module.css'

export default function Home() {
  const [loading, setLoading] = useState(true);
  const [data, setData] = useState({});

  useEffect(async () => {
    
    const res = await fetch("https://api.github.com/users/danecwalker/repos?sort=created");
    const _json = await res.json();

    setData(_json.slice(0, 4));
    setLoading(false);
  
  }, [])
  

  return (
    <div>
      <Head>
        <title>Dane Walker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main id={styles.container}>
        <div id={styles.intro}>
          <h1>Dane Walker</h1>
          <h3>Mechatronics Engineering / Computer Science Student</h3>
          <h3>Based in 📍 Brisbane, Australia</h3>
        </div>

        <div id={styles.latest}>
          <h2>Latest Projects</h2>
          { loading ? <div id={styles.loader}><Triangle color="#000" /></div> : 
            <>
              <div id={styles.projects}>
                {
                  data.map((d) => (
                    <a href={`/project/${d.name}`}>
                      <div id={styles.project}>
                        <h3>{d.name}</h3>
                        <p>{d.description}</p>
                        <p id={styles.language_badge} style={{backgroundColor: `${colours[d.language].color}33`, color: colours[d.language].color, border: `1px solid ${colours[d.language].color}`}}>{d.language}</p>
                      </div>
                    </a>
                  ))
                }
              </div>
            </>
          }
        </div>
      </main>

      <footer id={styles.footer}>
        <p>&copy; Copyright 2022, Dane Walker</p>
      </footer>
      
    </div>
  )
}
