import Head from 'next/head'
import styles from '../styles/Projects.module.css';

import { Triangle } from  'react-loader-spinner'
import { useState, useEffect } from 'react';

function Projects() {

  const [loading, setLoading] = useState(true)

  useEffect(() => {
    
    setTimeout(()=>{setLoading(false)},2000)
  
  }, [])
  

  return (
    <div>
      <Head>
        <title>Dane Walker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main id={styles.container}>
        <div id={styles.intro}>
          <h1>Projects</h1>
        </div>


        
          { loading ? <div id={styles.loader}><Triangle color="#000" /></div> :
            null
          }

          
          <div id={styles.projects}>
          <div id={styles.project}>
            <h3>MNet</h3>
            <p>An MNIST feedforward model coded in python and served via Flask.</p>
            <p id={styles.language_badge}>Python</p>
          </div>

          <a href="/project/1">
            <div id={styles.project}>
              <h3>MNet</h3>
              <p>An MNIST feedforward model coded in python and served via Flask.</p>
              <p id={styles.language_badge}>Python</p>
            </div>
          </a>
        </div>
        
      </main>

      <footer id={styles.footer}>
        <p>&copy; Copyright 2022, Dane Walker</p>
      </footer>
      
    </div>
  )
}

export default Projects;