import styles from '../../styles/Project.module.css'

import { useRouter } from 'next/router'
import Head from 'next/head'
import { useEffect, useState } from 'react';
import { Triangle } from  'react-loader-spinner'
import colours from '../../components/colours';

function ProjectPage() {
  const router = useRouter();
  const { pid } = router.query;

  const [project, setProject] = useState({})
  const [loading, setLoading] = useState(true);

  useEffect(async () => {

    if (colours["Python"]) {
      setProject({
        name: "MNet",
        description: "An MNIST feedforward model coded in python and served via Flask.",
        language: "Python",
        colour: colours["Python"].color,
        html_url: "https://github.com/danecwalker/MNet",
        homepage: "https://mnet-draw.herokuapp.com/",
        screenshot: "https://raw.githubusercontent.com/danecwalker/MNet/master/screenshots/screenshot_4.png",
      })
    }
    

  }, [])
  

  return (
    <div>
      <Head>
        <title>Dane Walker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      { loading ? <div id={styles.loader}><Triangle color="#000" /></div> :
        null
      }

      <main id={styles.container}>
          <div id={styles.intro}>
            <h1>{project.name}</h1>
            <h3>{project.description}</h3>
            <h6 id={styles.language_badge} style={{backgroundColor: `${project.colour}33`, color: project.colour, border: `1px solid ${project.colour}`}}>{project.language}</h6>
          </div>

          <div id={styles.links}>
            <div id={styles.link_item}><a href={project.html_url}>🔗 {project.html_url}</a></div>
            <div id={styles.link_item}><a href={project.homepage}>🔗 {project.homepage}</a></div>
          </div>

          <div id={styles.preview}>
            <img src={project.screenshot} onLoad={()=>{setLoading(false)}}/>
          </div>
      </main>
    </div>
  )
}

export default ProjectPage;